//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskAPIs1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string ArticleName { get; set; }
        public string ArticleCategory { get; set; }
        public string ArticleContent { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> commentApproval { get; set; }
        public string Reason { get; set; }
    }
}
